### ISSUE TITLE
QQ on generating proper struct

### ISSUE THREAD

**Issue by atmosx** [shurcooL/githubv4#55]
Hello,

I'm trying to convert the following GraphQL expression to Golang `struct`:

```
query{
  search(first: 100, type: REPOSITORY, query: "topic:golang org:google") {
    pageInfo {
      hasNextPage
      endCursor
      }
    repos: edges {
      repo: node {
        ... on Repository {
          name
          url
          id
        }
      }
    }
  }
}
```

I came up with something like this:

```Go
package main

import (
	"context"

	"fmt"

	"github.com/shurcooL/githubv4"
	"golang.org/x/oauth2"
)

var q struct {
	Search struct {
		PageInfo struct {
			HasNextPage bool
			EndCursor   githubv4.String
		}
		Repos []struct {
			Repo []struct {
				Repository struct {
					Name githubv4.String
				} `graphql:"... on Repository"`
			} `graphql:"repo: node"`
		} `graphql:"repos: edges"`
	} `graphql:"search(first: 3, type: REPOSITORY, query: \"topic:golang org:google\")"`
}

func main() {
	token := "123"
	ctx := context.Background()
	ts := oauth2.StaticTokenSource(
		&oauth2.Token{AccessToken: token},
	)
	tc := oauth2.NewClient(ctx, ts)

	client := githubv4.NewClient(tc)
	err := client.Query(context.Background(), &q, nil)
	if err != nil {
		fmt.Println(err)
	}
	fmt.Println(q.Search.Repos)
}

```

However, I'm getting back an empty struct:

```
$ go run main.go
struct field for "name" doesn't exist in any of 1 places to unmarshal
[{[]}]
```

Ideas, thoughts? 

Thank you for your time & Happy new year!

P.

**Comment by dmitshur** [comment]
Hi @atmosx,

Thanks for providing the exact GraphQL query and the Go code you tried, it made investigating this very easy.

The problem is here:

```diff
-Repo []struct {
+Repo struct {
```

It is because the `graphql:"repo: node"` field corresponds to a [`SearchResultItemEdge.node`](https://developer.github.com/v4/object/searchresultitemedge/#node), which a single `SearchResultItem`, not a list.

It's unfortunate the error message is not more helpful in spotting where the problem is. I have added a comment in https://github.com/shurcooL/graphql/issues/46#issuecomment-570762336 to investigate if it's possible to improve that.

**Comment by dmitshur** [comment]
Slightly off topic, I want to point out you could simplify that query by using the [`nodes`](https://developer.github.com/v4/object/searchresultitemconnection/#nodes) field directly (since the only field in `edges` being used is `node`\):

```GraphQL
nodes {
	... on Repository {
		name
	}
}
```

Its Go code equivalent:

```Go
Repos []struct {
	Repository struct {
		Name githubv4.String
	} `graphql:"... on Repository"`
} `graphql:"repo: nodes"`
```

**Comment by atmosx** [comment]
Thanks @dmitshur for the prompt reply and simplified version of the query!

I'm closing the issue as it is solved.
