### ISSUE TITLE
Does graphql API have rest API V3 / users

### ISSUE THREAD

**Issue by JeffreyBool** [shurcooL/githubv4#80]
Does graphql API have rest API V3 / users

https://developer.github.com/v3/users/

Lists all users, in the order that they signed up on GitHub. This list includes personal user accounts and organization accounts.

Note: Pagination is powered exclusively by the since parameter. Use the Link header to get the URL for the next page of users.

GraphQL API

**Comment by dmitshur** [comment]
This is an issue tracker for a Go package that provides access to the GitHub GraphQL API V4.

Threre are better places to seek information and ask questions about the GitHub API:

-	https://docs.github.com
-	https://github.community/c/github-api-development-and-support/37

I'll close this since it's out of scope for this issue tracker. Thanks.
